name: FTPS Test

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: ./
        with:
          server: "81.169.252.12"
          username: kc_admin_ftp
          password: ${{ secrets.ftp_password }}
          protocol: ftps
